name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: saper-apk
          path: ${{ steps.buildozer.outputs.filename }}
